spring:
  application:
    name: zuul-server
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
zuul:
  routes:
    user:  #自定义路由规则的名称，在底层是一个Map的key
      serviceId: customer  #目标微服务名称，ZuulRoute类型的一个属性
      path: /zuul-customer/**  # 用来代替目标微服务名称的路径，ZuulRoute类型的一个属性
    #ignored-services:     # 忽略指定微服务名称，让用户不能通过微服务名称访问
    # - consumer-service
  ignored-services: '*'  # 忽略所有微服务名称
  prefix: /jinronga      # 给访问路径添加统一前缀